<a href="https://colab.research.google.com/github/srinukindia/PY_PRACTICE/blob/main/pandas/pd_001.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

In [ ]:
import numpy as np
a= np.ones((5,5))
z=np.zeros((3,3))
z[1,1]= 9
a[1:-1,1:-1]=z
print(a)


In [ ]:
c= np.array([1,2,3,4,5])
d=c.copy()
d[0]=100
print(c)

In [ ]:
e= np.ones((2,3))
f= np.full((3,2),2)
print(np.matmul(e,f))

In [ ]:
g= np.identity(3)
#print(g)
print(np.linalg.det(g))

1.0


In [ ]:
h= np.array([1,2,3])
i= np.array([4,5,6])
print(h*i)

In [ ]:
j= np.array([[1,2,3],[4,5,6]])
print(j.sum(axis=1))
print(j.min(axis=0))

In [ ]:
#re oganize arrays
k= np.array([[1,2,3,4],[5,6,7,8]])
print(k.shape)
l= k.reshape((4,2))
print(l)
print(k.T)

In [ ]:
m1= np.array([1,2,3,4])
m2= np.array([5,6,7,8])
np.vstack((m1,m2))
np.hstack((m1,m2))

array([1, 2, 3, 4, 5, 6, 7, 8])

In [ ]:
#dealing with files in numpy (first upload files to google colab)
import os
print(os.getcwd())
os.listdir()
#from google.colab import files
#files.upload()
n= np.genfromtxt("sample_data_np.txt", delimiter=",")
print(n)
#Boolean masking
n>5


/content
[[1. 2. 3.]
 [4. 5. 6.]]


array([[False, False, False],
       [False, False,  True]])

In [ ]:
#Boolean masking and advanced indexing
o= np.array([1,2,3]) #alphabet o not 0
print(o>1)
print(o[o>1])
p= np.array([[1,2,3],[4,5,6]])
print(np.all(p>3, axis=0))

[False  True  True]
[2 3]
[False False False]


In [ ]:
q= np.array([[1,2,3],[4,5,6]])
print( (q>3) & (q<6))

[[False False False]
 [ True  True False]]
